name: Deploy to Velixir

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Velixir CLI
        run: |
          curl -fsSL https://velixir.net/install.sh | sh
          echo "$HOME/.velixir/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.velixir/bin:$PATH"
          velixir --version

      - name: Deploy
        run: velixir deploy --prod --app 3ad5283b-0d07-424c-851c-04257424aa25
        env:
          VELIXIR_TOKEN: ${{ secrets.VELIXIR_API_KEY }}